### ISSUE TITLE
Installing on Debian Jesse on raspberry pi 2 throws error

### ISSUE THREAD

**Issue by MatthewSteeples** [RPi-Distro/python-energenie#11]
Running setup.py install for RPi.GPIO
    building 'RPi.GPIO' extension
    arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.4m -c source/py_gpio.c -o build/temp.linux-armv7l-3.4/source/py_gpio.o
    error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
    Complete output from command /usr/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip-build-pbw__v2m/RPi.GPIO/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-fxz607zs-record/install-record.txt --single-version-externally-managed --compile:
    running install

Will I be safe to just symlink `gcc` to `arm-linux-gnueabihf-gcc` and try again?

**Comment by MatthewSteeples** [comment]
My mistake, turns out I didn't have the `build-essentials` package installed so didn't have any `gcc` installed at all! I've since installed that and now have a different error.

    Installing collected packages: RPi.GPIO
    Running setup.py install for RPi.GPIO
    building 'RPi.GPIO' extension
    arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.4m -c source/py_gpio.c -o build/temp.linux-armv7l-3.4/source/py_gpio.o
    source/py_gpio.c:23:20: fatal error: Python.h: No such file or directory
     #include "Python.h"
                        ^
    compilation terminated.
    error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
    Complete output from command /usr/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip-build-t_gv5ox_/RPi.GPIO/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-qlt4uikp-record/install-record.txt --single-version-externally-managed --compile:
    running install

**Comment by MatthewSteeples** [comment]
And all solved now, installed the `python-dev` package and all installed successfully

**Comment by bennuttall** [comment]
Hmm. I don't know why this occurs in Jessie. I'm sure it wasn't required in Wheezy. Maybe because the pip version of the latest RPi.GPIO isn't available. Thanks for the report, I'll look into it.

**Comment by aQuaYi** [comment]
sudo apt-get update 
sudo apt-get install -t jessie python-dev

the way to install python-dev on jessie

**Comment by melzoghbi** [comment]
check step 3 on this blog post: https://medium.com/@melzoghbi/deploy-iot-edge-on-raspberry-pi-e9cc9004ea3a

**Comment by FuriosoJack** [comment]
For those that have not worked at all you have to install these packages

 `sudo apt-get install libzbar-dev libzbar0`

Instalen esas librerias

**Comment by iamnimnul** [comment]
`sudo apt-get install python-dev`

or if you’re using python3 then:

`sudo apt-get install python3-dev`
