### ISSUE TITLE
GPIO mode causing conflicts

### ISSUE THREAD

**Issue by GlynHanmer** [RPi-Distro/python-energenie#12]
By using GPIO mode BCM rather than BOARD the energenie module isn't compatible with the original Raspberry Pi's. It's took me an evening to fault find why and it came down to this.

I've seen that in your commit log you changed from BOARD to BCM at one point. May I ask what the reason for this decision was?

http://www.raspberrypi-spy.co.uk/2012/06/simple-guide-to-the-rpi-gpio-header-and-pins/

Thanks,
Glyn.

**Comment by bennuttall** [comment]
The Raspberry Pi Foundation recommends BCM mode, and uses it in all its resources.

Note this library is deprecated in favour of [GPIO Zero](http://gpiozero.readthedocs.io/) which recently added [Energenie support](http://gpiozero.readthedocs.io/en/v1.2.0/api_boards.html#energenie)
