### ISSUE TITLE
error on pythonhosted.org install page

### ISSUE THREAD

**Issue by broo0ose** [RPi-Distro/python-energenie#13]
I tried the pip install on python3 using the commands suggested, not sure if the command name has changed but I needed to use the command 'sudo pip3 install energenie' rather than 'sudo pip-3.2 install energenie'

**Comment by bennuttall** [comment]
In Raspbian Wheezy, pip for Python 3 was `pip-3.2`. In Jessie that' oddity is fixed and it's just `pip3`. However, we added an alias for `pip-3.2` -> `pip3` in Jessie, but since Jessie Lite doesn't come with `pip` installed, this alias doesn't exist.
