### ISSUE TITLE
get current status for a toggle ?

### ISSUE THREAD

**Issue by squillopmedia** [RPi-Distro/python-energenie#14]
is there a way to get the current status of socket(#) so then it can be toggled to opposite?
or is there just a toggle command ?

thanks

**Comment by bennuttall** [comment]
No - the regular Energenie sockets are not able to communicate their state. I believe the [Adapter Plus](https://energenie4u.co.uk/catalogue/product/MIHO005-RT) has this feature.

FYI this library is deprecated in favour of [GPIO Zero](http://gpiozero.readthedocs.io/) which recently added [Energenie support](http://gpiozero.readthedocs.io/en/v1.2.0/api_boards.html#energenie)
